-- CREATE DATABASE E_SPORT_GAMES --

CREATE DATABASE E_SPORT_GAMES;


-- TABLE USER --

DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
    ID SERIAL,
    EMAIL CHARACTER VARYING(30) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY(ID)
);

-- TABLE GAME --

DROP TABLE IF EXISTS GAME CASCADE;

CREATE TABLE GAME (
	ID SERIAL,
	ID_USER INTEGER,
	NAME CHARACTER VARYING(100) NOT NULL UNIQUE,
	DESCRIPTION CHARACTER VARYING NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	CONSTRAINT PK_GAME PRIMARY KEY(ID),
	CONSTRAINT FK_GAME_USERS FOREIGN KEY (ID_USER) REFERENCES USERS (ID)
);

-- TABLE GAME_CHARACTER --

DROP TABLE IF EXISTS GAME_CHARACTER CASCADE;

CREATE TABLE GAME_CHARACTER (
	ID SERIAL,
	ID_GAME INTEGER,
	NAME CHARACTER VARYING(100) NOT NULL,
	DESCRIPTION CHARACTER VARYING NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	CONSTRAINT PK_GAME_CHARACTER PRIMARY KEY(ID),
	CONSTRAINT FK_GAME_CHARACTER_GAME FOREIGN KEY(ID_GAME) REFERENCES GAME(ID)
);