-- CREATE DATABASE E_SPORT_GAMES --

CREATE DATABASE E_SPORT_GAMES;

-- TABLE GAME --
	
DROP TABLE IF EXISTS GAME CASCADE;	
	
CREATE TABLE GAME (
	ID SERIAL,
	NAME CHARACTER VARYING(100) NOT NULL UNIQUE,
	DESCRIPTION CHARACTER VARYING NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP,
	CONSTRAINT PK_GAME PRIMARY KEY(ID)	
);

-- TABLE GAME_CHARACTER --

DROP TABLE IF EXISTS GAME_CHARACTER CASCADE;

CREATE TABLE GAME_CHARACTER (
	ID SERIAL,
	ID_GAME INTEGER, 
	NAME CHARACTER VARYING(100) NOT NULL,
	DESCRIPTION CHARACTER VARYING NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP,
	CONSTRAINT PK_GAME_CHARACTER PRIMARY KEY(ID),
	CONSTRAINT FK_GAME_CHARACTER_GAME FOREIGN KEY(ID_GAME) REFERENCES GAME(ID)	
);